arduino_bridge:
  ros__parameters:
    port: "/dev/ttyACM0"
    baud_rate: 115200
    timeout: 1.0
    write_timeout: 1.0
    start_delimiter: "<"
    end_delimiter: ">"
    field_separator: ","
    motor_max: 255
    motor_min: 0
    encoder_ticks_per_rev: 20
    wheel_circumference: 0.314
    wheel_base: 0.2
    wheel_radius: 0.033
    max_speed: 0.5
    max_angular_speed: 1.0
    debug: true
    pid:
      kp: 1.0
      ki: 0.1
      kd: 0.05
      sample_time: 0.1