# ROS 2 Arduino Bridge Parameters

# Serial port configuration
port: /dev/ttyACM0
baud_rate: 115200

# Debug mode (prints additional debug information)
debug: false

# Frame IDs
odom_frame_id: 'odom'
base_frame_id: 'base_link'
imu_frame_id: 'imu_link'

# Covariance values (adjust based on your robot's sensors)
odom_pose_covariance: [0.1, 0.0, 0.0, 0.0, 0.0, 0.0,
                      0.0, 0.1, 0.0, 0.0, 0.0, 0.0,
                      0.0, 0.0, 0.1, 0.0, 0.0, 0.0,
                      0.0, 0.0, 0.0, 0.1, 0.0, 0.0,
                      0.0, 0.0, 0.0, 0.0, 0.1, 0.0,
                      0.0, 0.0, 0.0, 0.0, 0.0, 0.1]

odom_twist_covariance: [0.1, 0.0, 0.0, 0.0, 0.0, 0.0,
                       0.0, 0.1, 0.0, 0.0, 0.0, 0.0,
                       0.0, 0.0, 0.1, 0.0, 0.0, 0.0,
                       0.0, 0.0, 0.0, 0.1, 0.0, 0.0,
                       0.0, 0.0, 0.0, 0.0, 0.1, 0.0,
                       0.0, 0.0, 0.0, 0.0, 0.0, 0.1]

# IMU parameters
publish_imu: true
imu_accel_covariance: 0.1  # m/s^2
imu_gyro_covariance: 0.01  # rad/s
