#!/usr/bin/env python3
"""
Object Detector Executable Wrapper
"""
import sys
import os

# Add the package to Python path
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))

from robot_perception.nodes.object_detector import main

if __name__ == '__main__':
    main()