# DWB Controller Parameters
controller_server:
  ros__parameters:
    use_sim_time: False
    controller_frequency: 20.0
    min_x_velocity_threshold: 0.001
    min_y_velocity_threshold: 0.5
    min_theta_velocity_threshold: 0.001
    progress_checker_plugin: "progress_checker"
    goal_checker_plugin: "goal_checker"
    controller_plugins: ["FollowPath"]
    FollowPath:
      plugin: "dwb_core::DWBLocalPlanner"
      debug_trajectory_details: True
      min_vel_x: -0.2
      max_vel_x: 0.2
      min_vel_y: 0.0
      max_vel_y: 0.0
      max_vel_theta: 0.5
      min_speed_xy: 0.0
      max_speed_xy: 0.2
      min_speed_theta: 0.0
      acc_lim_x: 0.1
      acc_lim_y: 0.0
      acc_lim_theta: 0.2
      decel_lim_x: -0.1
      decel_lim_y: 0.0
      decel_lim_theta: -0.2
      vx_samples: 20
      vy_samples: 5
      vtheta_samples: 20
      sim_time: 1.7
      linear_granularity: 0.05
      angular_granularity: 0.1
      transform_tolerance: 0.2
      xy_goal_tolerance: 0.1
      yaw_goal_tolerance: 0.1
      prune_plan: True
      prune_distance: 1.0
      short_circuit_trajectory_evaluation: True
      debug_trajectory_details: False
      path_distance_bias: 32.0
      goal_distance_bias: 24.0
      occdist_scale: 0.01
      forward_point_distance: 0.1
      max_vel_theta: 0.5
      min_vel_theta: -0.5
      acc_lim_theta: 0.5
      decel_lim_theta: -0.5
      vtheta_samples: 20
      angular_sim_granularity: 0.1
      sim_time: 1.7
      sim_granularity: 0.025
      path_distance_bias: 32.0
      goal_distance_bias: 24.0
      occdist_scale: 0.01
      forward_point_distance: 0.1
      scaling_speed: 0.25
      max_scaling_factor: 0.2
      rotation_lookahead_dist: 0.5
      allow_init_backwards_motion: False
      max_vel_x_backwards: 0.1
      min_speed_xy: 0.0
      max_speed_xy: 0.2
      min_speed_theta: 0.0
      
      # Goal checker parameters
      goal_checker:
        plugin: "nav2_controller::SimpleGoalChecker"
        xy_goal_tolerance: 0.1
        yaw_goal_tolerance: 0.1
        stateful: True
      
      # Progress checker parameters
      progress_checker:
        plugin: "nav2_controller::SimpleProgressChecker"
        required_movement_radius: 0.5
        movement_time_allowance: 10.0
      
      # Costmap parameters
      global_frame: odom
      robot_base_frame: base_link
      transform_tolerance: 0.1
      
      # Trajectory generation parameters
      min_sampling_granularity: 0.01
      yaw_goal_tolerance: 0.1
      xy_goal_tolerance: 0.1
      
      # Oscillation parameters
      oscillation_reset_dist: 0.05
      oscillation_reset_angle: 0.1
