# Common parameters for both global and local costmaps
obstacle_layer:
  enabled: True
  max_obstacle_height: 0.6
  obstacle_range: 2.5
  raytrace_range: 3.0
  track_unknown_space: False

  # Sensor configurations
  observation_sources: scan
  scan: 
    data_type: LaserScan
    topic: /scan
    marking: True
    clearing: True
    inf_is_valid: False

inflation_layer:
  enabled: True
  cost_scaling_factor: 3.0
  inflation_radius: 0.55

static_layer:
  enabled: True
  map_topic: /map
  subscribe_to_updates: True
  track_unknown_space: True
  use_maximum: False
  unknown_cost_value: -1
  trinary_costmap: True

# Robot footprint (circular)
footprint: [[0.2, 0.2], [0.2, -0.2], [-0.2, -0.2], [-0.2, 0.2]]
robot_radius: 0.2

# Update and publish frequencies
update_frequency: 10.0
publish_frequency: 5.0

# Global frame and transform settings
global_frame: map
robot_base_frame: base_link
transform_tolerance: 0.5

# Obstacle marking and clearing
marking: True
clearing: True

# Map type and resolution
map_type: costmap
resolution: 0.05

# Rolling window settings (for local costmap)
rolling_window: False
width: 10.0
height: 10.0

# Obstacle inflation settings
inflation_radius: 0.5
cost_scaling_factor: 5.0

# Other settings
always_send_full_costmap: True
lethal_cost_threshold: 100
unknown_cost_value: -1
trinary_costmap: True

# Footprint clearing
footprint_clearing_enabled: True

# Obstacle layer settings
max_obstacle_height: 0.6
obstacle_range: 2.5
raytrace_range: 3.0

# Sensor model settings
raytrace_min_range: 0.1
raytrace_max_range: 3.0
obstacle_min_range: 0.0
obstacle_max_range: 2.5

# Inflation settings
inflation_radius: 0.55
cost_scaling_factor: 5.0

# Static map settings
static_map: True
subscribe_to_updates: True

# Observation buffer settings
observation_sources: scan
scan: {data_type: LaserScan, topic: /scan, marking: True, clearing: True}
