# Global costmap parameters
global_costmap:
  ros__parameters:
    global_frame: map
    robot_base_frame: base_link
    update_frequency: 1.0
    publish_frequency: 1.0
    transform_tolerance: 0.5
    rolling_window: False
    always_send_full_costmap: True
    
    # Plugins
    plugins: ["static_layer", "obstacle_layer", "inflation_layer"]
    
    # Static map layer
    static_layer:
      plugin: "nav2_costmap_2d::StaticLayer"
      map_subscribe_transient_local: True
    
    # Obstacle layer
    obstacle_layer:
      plugin: "nav2_costmap_2d::ObstacleLayer"
      enabled: True
      observation_sources: scan
      scan:
        topic: /scan
        data_type: "LaserScan"
        marking: True
        clearing: True
        min_obstacle_height: 0.0
        max_obstacle_height: 2.0
        expected_update_rate: 0.0
        observation_persistence: 0.0
        inf_is_valid: False
        raytrace_range: 3.0
        obstacle_range: 2.5
    
    # Inflation layer
    inflation_layer:
      plugin: "nav2_costmap_2d::InflationLayer"
      enabled: True
      cost_scaling_factor: 3.0
      inflation_radius: 0.55
    
    # Resolution and size
    resolution: 0.05
    width: 10.0
    height: 10.0
    origin_x: -5.0
    origin_y: -5.0
    
    # Robot footprint
    footprint: "[[-0.2, -0.2], [-0.2, 0.2], [0.2, 0.2], [0.2, -0.2]]"
    robot_radius: 0.2
