# AMCL parameters
amcl:
  ros__parameters:
    use_sim_time: False
    alpha1: 0.2    # Rotation noise from rotation
    alpha2: 0.2    # Rotation noise from translation
    alpha3: 0.2    # Translation noise from translation
    alpha4: 0.2    # Translation noise from rotation
    alpha5: 0.1    # Translation noise from translation (strafing)
    
    # Laser model parameters
    laser_model_type: "likelihood_field"
    laser_likelihood_max_dist: 2.0
    laser_max_range: 10.0
    laser_min_range: 0.1
    max_beams: 60
    
    # Odometry model parameters
    odom_model_type: "diff"
    odom_alpha1: 0.2
    odom_alpha2: 0.2
    odom_alpha3: 0.2
    odom_alpha4: 0.2
    odom_frame_id: "odom"
    base_frame_id: "base_link"
    global_frame_id: "map"
    
    # Particle filter parameters
    min_particles: 500
    max_particles: 2000
    kld_err: 0.01
    kld_z: 0.99
    update_min_d: 0.2
    update_min_a: 0.5
    resample_interval: 1
    transform_tolerance: 0.1
    recovery_alpha_slow: 0.0
    recovery_alpha_fast: 0.0
    initial_pose_x: 0.0
    initial_pose_y: 0.0
    initial_pose_a: 0.0
    initial_cov_xx: 0.5 * 0.5
    initial_cov_yy: 0.5 * 0.5
    initial_cov_aa: (π/12) * (π/12)
    
    # Topic names
    scan_topic: "scan"
    map_topic: "map"
    
    # TF settings
    tf_broadcast: True
