# Main parameters
use_sim_time: False

# Configure default behavior of the navigation stack
default_nav_through_poses_bt_xml: ~/nav2_bt_navigator/behavior_trees/navigate_through_poses_w_replanning_and_recovery.xml
default_nav_to_pose_bt_xml: ~/nav2_bt_navigator/behavior_trees/navigate_to_pose_w_replanning_and_recovery.xml

# Configure the behavior of the planner server
planner_server:
  ros__parameters:
    expected_planner_frequency: 20.0
    use_sim_time: False
    planner_plugin_types: ["nav2_navfn_planner/NavfnPlanner"]
    planner_plugin_ids: ["GridBased"]
    planner_plugin_names: ["GridBased"]

# Configure the behavior of the controller server
controller_server:
  ros__parameters:
    use_sim_time: False
    controller_frequency: 20.0
    min_x_velocity_threshold: 0.001
    min_y_velocity_threshold: 0.5
    min_theta_velocity_threshold: 0.001
    controller_plugin_types: ["dwb_core::DWBLocalPlanner"]
    controller_plugin_ids: ["FollowPath"]
    controller_plugin_names: ["FollowPath"]

# Configure the behavior of the smoother server
smoother_server:
  ros__parameters:
    use_sim_time: False
    smoother_plugin_types: ["nav2_velocity_smoother/VelocitySmoother"]
    smoother_plugin_ids: ["SmoothPath"]
    smoother_plugin_names: ["SmoothPath"]

# Configure the behavior of the planner
planner:
  ros__parameters:
    use_sim_time: False
    planner_plugin: "nav2_navfn_planner/NavfnPlanner"
    planner_id: "GridBased"

# Configure the behavior of the controller
controller:
  ros__parameters:
    use_sim_time: False
    controller_plugin: "dwb_core::DWBLocalPlanner"
    controller_id: "FollowPath"
    min_x_velocity_threshold: 0.001
    min_y_velocity_threshold: 0.5
    min_theta_velocity_threshold: 0.001

# Configure the behavior of the behavior tree navigator
bt_navigator:
  ros__parameters:
    use_sim_time: False
    bt_loop_duration: 10
    default_bt_xml_filename: "navigate_w_replanning_and_recovery.xml"
    global_frame: "map"
    robot_base_frame: "base_link"
    odom_topic: "/odom"

# Configure the behavior of the waypoint follower
waypoint_follower:
  ros__parameters:
    use_sim_time: False
    loop_rate: 20.0
    stop_on_failure: False
    waypoint_task_executor_plugin: "waypoint_follower"

# Configure the behavior of the velocity smoother
velocity_smoother:
  ros__parameters:
    use_sim_time: False
    speed_limiter: 1.0
    odom_topic: "/odom"
    odom_duration: 0.1

# Configure the behavior of the costmap
costmap_common:
  ros__parameters:
    use_sim_time: False
    robot_radius: 0.2
    robot_base_frame: "base_link"
    update_frequency: 10.0
    publish_frequency: 10.0
    global_frame: "odom"
    transform_tolerance: 0.5
    map_topic: "map"
    subscribe_to_updates: True
    rolling_window: False
    always_send_full_costmap: True

# Configure the global costmap
global_costmap:
  ros__parameters:
    use_sim_time: False
    global_frame: "map"
    robot_base_frame: "base_link"
    update_frequency: 1.0
    publish_frequency: 1.0
    transform_tolerance: 0.5
    static_layer:
      enabled: True
      map_subscribe_transient_local: True
    obstacle_layer:
      enabled: True
      observation_sources: "scan"
      scan:
        topic: "scan"
        data_type: "LaserScan"
        marking: True
        clearing: True
    inflation_layer:
      enabled: True
      cost_scaling_factor: 3.0
      inflation_radius: 0.55

# Configure the local costmap
local_costmap:
  ros__parameters:
    use_sim_time: False
    global_frame: "odom"
    robot_base_frame: "base_link"
    update_frequency: 5.0
    publish_frequency: 2.0
    transform_tolerance: 0.5
    width: 3.0
    height: 3.0
    resolution: 0.05
    static_layer:
      enabled: False
    obstacle_layer:
      enabled: True
      observation_sources: "scan"
      scan:
        topic: "scan"
        data_type: "LaserScan"
        marking: True
        clearing: True
    inflation_layer:
      enabled: True
      cost_scaling_factor: 3.0
      inflation_radius: 0.55
