/**:
  ros__parameters:
    use_sim_time: False
    autostart: True
    bt_xml_filename: "navigate_w_replanning_and_recovery.xml"
    global_frame: map
    robot_base_frame: base_link
    robot_radius: 0.22
    transform_tolerance: 0.2
    planner_server:
      ros__parameters:
        expected_planner_frequency: 20.0
    controller_server:
      ros__parameters:
        controller_frequency: 20.0
