# Planner parameters for Nav2
planner_server:
  ros__parameters:
    use_sim_time: False
    expected_planner_frequency: 1.0
    
    # Planner plugins
    planner_plugins: ["GridBased"]
    
    # NavFn planner parameters
    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"
      tolerance: 0.5
      use_astar: False
      allow_unknown: True
      use_final_approach_orientation: False
      max_iterations: 1000000
      max_on_approach_iterations: 1000
      max_planning_time: 5.0
      
      # Cost function parameters
      cost_factor: 2.0
      neutral_cost: 50
      lethal_cost: 253
      costmap_topic: "global_costmap/costmap"
      footprint_topic: ""
      visualize_potential: False
      
      # Global planner parameters
      global_frame: "map"
      robot_base_frame: "base_link"
      transform_tolerance: 0.5
      
      # Path smoothing
      smooth_path: True
      min_distance_from_robot: 0.5
      
      # Path orientation modes
      use_final_approach_orientation: False
      allow_unknown: True
      
      # Costmap parameters
      costmap:
        global_frame: "map"
        robot_base_frame: "base_link"
        update_frequency: 1.0
        publish_frequency: 1.0
        transform_tolerance: 0.5
        static_map: True
        rolling_window: False
        track_unknown_space: True
        use_maximum: False
        unknown_cost_value: 255
        lethal_cost_threshold: 100
        trinary_costmap: True
        always_send_full_costmap: True
        
        # Plugins
        plugins: ["static_layer", "obstacle_layer", "inflation_layer"]
        
        # Static map layer
        static_layer:
          plugin: "nav2_costmap_2d::StaticLayer"
          map_subscribe_transient_local: True
        
        # Obstacle layer
        obstacle_layer:
          plugin: "nav2_costmap_2d::ObstacleLayer"
          enabled: True
          observation_sources: "scan"
          scan:
            topic: "/scan"
            data_type: "LaserScan"
            marking: True
            clearing: True
        
        # Inflation layer
        inflation_layer:
          plugin: "nav2_costmap_2d::InflationLayer"
          cost_scaling_factor: 3.0
          inflation_radius: 0.55

# Behavior tree navigator parameters
bt_navigator:
  ros__parameters:
    use_sim_time: False
    bt_loop_duration: 10
    default_bt_xml_filename: "navigate_w_replanning_and_recovery.xml"
    global_frame: "map"
    robot_base_frame: "base_link"
    odom_topic: "/odom"
    
    # Behavior tree parameters
    behavior_tree:
      bt_loop_duration: 100
      default_server_timeout: 20.0
      default_bt_xml_filename: "navigate_w_replanning_and_recovery.xml"
      global_frame: "map"
      robot_base_frame: "base_link"
      odom_topic: "/odom"
      
      # Recovery behavior parameters
      recovery_behavior:
        - name: "spin"
          plugin: "nav2_behaviors/Spin"
        - name: "backup"
          plugin: "nav2_behaviors/BackUp"
        - name: "wait"
          plugin: "nav2_behaviors/Wait"
      
      # Navigator parameters
      navigator:
        plugin: "nav2_bt_navigator/Navigator"
        use_sim_time: False
        bt_loop_duration: 100
        default_bt_xml_filename: "navigate_w_replanning_and_recovery.xml"
        global_frame: "map"
        robot_base_frame: "base_link"
        odom_topic: "/odom"
        
        # Navigator server parameters
        server:
          use_sim_time: False
          action_server_result_timeout: 900.0
          action_server_bt_xml: "navigate_w_replanning_and_recovery.xml"
          
          # Behavior tree parameters
          bt_loop_duration: 10
          default_bt_xml_filename: "navigate_w_replanning_and_recovery.xml"
          
          # Recovery behavior parameters
          recovery_behavior:
            - name: "spin"
              plugin: "nav2_behaviors/Spin"
            - name: "backup"
              plugin: "nav2_behaviors/BackUp"
            - name: "wait"
              plugin: "nav2_behaviors/Wait"
