# Laser filter configuration for RPLIDAR A1M8
scan_filter_chain:
  - name: range_filter
    type: laser_filters/LaserScanRangeFilter
    params:
      lower_threshold: 0.15  # 15cm minimum range
      upper_threshold: 12.0  # 12m maximum range
      use_message_range_limits: false

  - name: intensity_filter
    type: laser_filters/LaserScanIntensityFilter
    params:
      lower_threshold: 50.0  # Minimum intensity value
      upper_threshold: 100000.0  # Maximum intensity value

  - name: shadow_filter
    type: laser_filters/ScanShadowsFilter
    params:
      min_angle: 10.0  # degrees
      max_angle: 170.0  # degrees
      window: 1
      neighbors: 4
      keep_organized: true

  - name: angle_filter
    type: laser_filters/LaserScanAngularBoundsFilter
    params:
      lower_angle: -3.14159  # -180 degrees
      upper_angle: 3.14159   # 180 degrees

  - name: median_filter
    type: laser_filters/MedianFilterFloat
    params:
      number_of_observations: 3  # Number of scans to average
