# Object Detector Parameters
object_detector:
  ros__parameters:
    # Model parameters
    model_path: "yolov8n.pt"
    confidence_threshold: 0.5
    device: "cuda:0"  # Will auto-fallback to CPU if CUDA not available
    
    # Image processing
    input_width: 640
    input_height: 480
    use_mosaic: True  # Enable/disable mosaic augmentation
    
    # Control parameters
    max_linear_speed: 0.5  # m/s
    max_angular_speed: 1.0  # rad/s
    target_distance: 1.0  # meters
    
    # Optimization flags
    use_fp16: True
    use_int8: False
    freeze_backbone: True
    freeze_epochs: 10  # Number of epochs to keep backbone frozen
    
    # Debug
    debug_mode: True
    visualize_detections: True
