arduino_driver:
  ros__parameters:
    baud_rate: 115200
    debug: true
    encoder_ticks_per_rev: 20
    max_angular_speed: 1.0
    max_speed: 0.5
    motor_max: 255
    motor_min: 0
    pid:
      kd: 12.0
      ki: 0.0
      ko: 50
      kp: 20.0
      sample_time: 0.1
    pid_kd: 12
    pid_ki: 0
    pid_ko: 50
    pid_kp: 20
    port: /dev/ttyACM0
    reconnect_interval: 5.0
    timeout: 1.0
    use_rosarduino_bridge: true
    wheel_base: 0.26
    wheel_circumference: 0.207
    wheel_radius: 0.033
    write_timeout: 1.0
